nelmio_api_doc:
    models: { use_jms: true }
    documentation:
        info:
            title: 'Pokemon Api'
            description: 'Awesome Api!'
            version: '1.0'
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]

    areas:
        path_patterns:
            - ^/api(?!/doc$)
