version: '3.7'

services:
    nginx:
        container_name: artsper_container_nginx
        image: nginx:stable-alpine
        restart: on-failure
        volumes:
            - ./public:/srv:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    php:
        container_name: artsper_container_php
        build: docker/php
        volumes:
            - ./:/srv
        depends_on:
            - mysql

    mysql:
        container_name: artsper_container_mysql
        image: 'mysql:8.0.19'
        command: ["--default-authentication-plugin=mysql_native_password"]
        restart: on-failure
        environment:
            MYSQL_DATABASE: artsper
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - database:/var/lib/mysql

volumes:
    database: ~
